{{- if and .Values.argoRollouts.enabled .Values.argoRollouts.analysisTemplates.enabled }}
{{- include "argoRollouts.validate" . -}}
---
# ============================================================================
# Error Rate Analysis Template
# ============================================================================
# Monitors HTTP 5xx error rate during canary rollout
# Triggers automatic rollback if error rate exceeds threshold
{{- if .Values.argoRollouts.analysisTemplates.errorRate.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Release.Name }}-error-rate-analysis
  labels: {{ include "kong.labels" $ | nindent 4 }}
spec:
  args:
    - name: service-name
      value: {{ .Release.Name }}-proxy
    - name: namespace
      value: {{ .Release.Namespace }}
    {{- if and .Values.argoRollouts.analysisTemplates.errorRate.authentication .Values.argoRollouts.analysisTemplates.errorRate.authentication.enabled }}
    # Reference credentials from Kubernetes secret for Prometheus authentication

    - name: prometheusBasic
      valueFrom:
        secretKeyRef:
          name: {{ .Values.argoRollouts.analysisTemplates.errorRate.authentication.secretName }}
          key: {{ .Values.argoRollouts.analysisTemplates.errorRate.authentication.basicKey }}
    {{- end }}

  # ============================================================================
  # Metrics Configuration
  # ============================================================================
  metrics:
  - name: error-rate
    # -- How often to evaluate the metric
    interval: {{ .Values.argoRollouts.analysisTemplates.errorRate.interval | default "30s" }}
    
    # -- Total number of measurements to take
    count: {{ .Values.argoRollouts.analysisTemplates.errorRate.count | default 0 }}
    
    # -- Number of failures that trigger rollback
    failureLimit: {{ .Values.argoRollouts.analysisTemplates.errorRate.failureLimit | default 2 }}
    
    # -- Success condition (result must be less than threshold)
    successCondition: {{ .Values.argoRollouts.analysisTemplates.errorRate.successCondition | default "result < 0.05" | quote }}
    
    # -- Metric provider configuration (Prometheus)
    provider:
      prometheus:
        # -- Prometheus server address
        address: {{ .Values.argoRollouts.analysisTemplates.errorRate.prometheusAddress | quote }}
        
        # -- PromQL query to calculate error rate
        query: |
          {{- tpl .Values.argoRollouts.analysisTemplates.errorRate.query . | nindent 10 }}
        
        {{- if and .Values.argoRollouts.analysisTemplates.errorRate.authentication .Values.argoRollouts.analysisTemplates.errorRate.authentication.enabled }}
        headers:
          - key: Authorization
            value: "Basic {{`{{  args.prometheusBasic }}`}}"
        {{- end }}
{{- end }}
---
# ============================================================================
# Success Rate Analysis Template
# ============================================================================
# Monitors overall HTTP success rate (non-5xx responses) during canary rollout
# Triggers automatic rollback if success rate falls below threshold
{{- if .Values.argoRollouts.analysisTemplates.successRate.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Release.Name }}-success-rate-analysis
  labels: {{ include "kong.labels" $ | nindent 4 }}
spec:
  # ============================================================================
  # Arguments
  # ============================================================================
  # Can be passed from Rollout resource for dynamic configuration
  args:
  - name: service-name
    value: {{ .Release.Name }}-proxy
  - name: namespace
    value: {{ .Release.Namespace }}
  {{- if and .Values.argoRollouts.analysisTemplates.successRate.authentication .Values.argoRollouts.analysisTemplates.successRate.authentication.enabled }}
  # Reference credentials from Kubernetes secret for Prometheus authentication
  - name: prometheusBasic
    valueFrom:
      secretKeyRef:
        name: {{ .Values.argoRollouts.analysisTemplates.successRate.authentication.secretName }}
        key: {{ .Values.argoRollouts.analysisTemplates.successRate.authentication.basicKey }}
  {{- end }}
  
  # ============================================================================
  # Metrics Configuration
  # ============================================================================
  metrics:
  - name: success-rate
    # -- How often to evaluate the metric
    interval: {{ .Values.argoRollouts.analysisTemplates.successRate.interval | default "30s" }}
    
    # -- Total number of measurements to take
    count: {{ .Values.argoRollouts.analysisTemplates.successRate.count | default 0 }}
    
    # -- Number of failures that trigger rollback
    failureLimit: {{ .Values.argoRollouts.analysisTemplates.successRate.failureLimit | default 3 }}
    
    # -- Success condition (result must be greater than threshold)
    successCondition: {{ .Values.argoRollouts.analysisTemplates.successRate.successCondition | default "result > 0.95" | quote }}
    
    # -- Metric provider configuration (Prometheus)
    provider:
      prometheus:
        # -- Prometheus server address
        address: {{ .Values.argoRollouts.analysisTemplates.successRate.prometheusAddress | quote }}
        
        # -- PromQL query to calculate success rate
        query: |
          {{- tpl .Values.argoRollouts.analysisTemplates.successRate.query . | nindent 10 }}
        
        {{- if and .Values.argoRollouts.analysisTemplates.successRate.authentication .Values.argoRollouts.analysisTemplates.successRate.authentication.enabled }}
        headers:
          - key: Authorization
            value: "Basic {{`{{ args.prometheusBasic }}`}}"
        {{- end }}
{{- end }}
{{- end }}
