{{/*
SPDX-FileCopyrightText: 2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/}}

{{- if include "cosign.enabled" $ }}
{{- $valueKeys := list -}}
{{- range .Values.imageVerification.publicKeys -}}
{{- if eq .source "value" -}}
{{- $valueKeys = append $valueKeys . -}}
{{- end -}}
{{- end -}}
{{- if $valueKeys }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cosign-public-key
  labels: {{ include "app.labels.standard" $ | nindent 4 }}
data:
{{- range $i, $entry := $valueKeys }}
  cosign.pub.{{ $i }}: |
    {{- $entry.value | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
