{{/*
SPDX-FileCopyrightText: 2025 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "app.labels.standard" $ | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{ include "app.labels.selectorLabels" $ | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if .Values.networkPolicy.ingress }}
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
    {{- else }}
    # Default: Allow proxy traffic
    - ports:
      {{- if .Values.proxy.tls.enabled }}
        - port: 8443
          protocol: TCP
      {{- else }}
        - port: 8000
          protocol: TCP
      {{- end }}
    {{- if .Values.adminApi.enabled }}
    # Allow admin API traffic
    - ports:
      {{- if .Values.adminApi.tls.enabled }}
        - port: 8444
          protocol: TCP
      {{- else }}
        - port: 8001
          protocol: TCP
      {{- end }}
    {{- end }}
    {{- if .Values.plugins.prometheus.enabled }}
    # Allow metrics scraping
    - ports:
        - port: {{ .Values.plugins.prometheus.port | default 9542 }}
          protocol: TCP
    {{- end }}
    # Allow status endpoint (health checks)
    - ports:
        - port: 8100
          protocol: TCP
    {{- if .Values.jumper.enabled }}
    # Allow jumper traffic
    - ports:
        - port: {{ .Values.jumper.port }}
          protocol: TCP
    {{- end }}
    {{- if .Values.issuerService.enabled }}
    # Allow issuer service traffic
    - ports:
        - port: {{ .Values.issuerService.port | default 8081 }}
          protocol: TCP
    {{- end }}
    {{- end }}
  egress:
    {{- if .Values.networkPolicy.egress }}
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
    {{- else }}
    # Default: Allow all egress
    - {}
    {{- end }}
{{- end }}
