{{/*
SPDX-FileCopyrightText: 2023-2025 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/}}

{{- if or (eq .Values.sslVerify true) .Values.plugins.zipkin.luaSslTrustedCertificate .Values.externalDatabase.sslVerify }}
apiVersion: v1
kind: Secret
metadata:
  {{- $name := printf "%s-%s" .Release.Name "trusted-ca-certificates" }}
  name: {{ $name }}
  labels: {{- include "app.labels.standard" $ | nindent 4 }}
  annotations: {{ include "argo.pathToSecret" $ | nindent 4 }}
type: Opaque
data:
{{- if eq .Values.sslVerify true }}
  trusted-ca-certificates.pem: {{ (.Values.trustedCaCertificates | default "# Set trustedCaCertificates in values.yaml") | b64enc }}
{{- end }}
{{- if or .Values.plugins.zipkin.luaSslTrustedCertificate .Values.externalDatabase.sslVerify }}
  lua-ssl-trusted-certificates.pem: {{ (include "kong.luaSslTrustedCertificates" $  | default "# Set luaSslTrustedCertificate in values.yaml") | b64enc }}
{{- end }}
{{- end -}}