{{/*
SPDX-FileCopyrightText: 2023-2025 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-proxy
  labels: {{ include "app.labels.standard" $ | nindent 4 }}
spec:
  selector: {{ include "app.labels.selectorLabels" $ | nindent 4 }}
  ports:
{{- if .Values.proxy.tls.enabled }}
  - name: proxy-ssl
    port: 8443
    targetPort: 8443
{{- else }}
  - name: proxy
    port: 8000
    targetPort: 8000
{{- end }}
    protocol: TCP