{{/*
SPDX-FileCopyrightText: 2023-2025 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/}}

{{- if and (.Values.plugins.prometheus.enabled) (.Values.plugins.prometheus.serviceMonitor.enabled) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metrics
  labels: {{ include "app.labels.standard" $ | nindent 4 }}
spec:
  selector: {{ include "app.labels.selectorLabels" $ | nindent 4 }}
  ports:
  - name: metrics
    port: 9542
    targetPort: metrics
    protocol: TCP
  - name: jumper-metrics
    port: 9544
    targetPort: jumper
    protocol: TCP
{{- end -}}
