# SPDX-FileCopyrightText: 2022 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: CC0-1.0

name: Lint Helm Chart

on: pull_request

permissions:
  contents: read

env:
  HELM_OPTIONS: "--set global.failOnUnsetValues=false --set keyRotation.enabled=true"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Helm
        uses: azure/setup-helm@v4
        
      - name: Lint Helm Chart
        run: helm lint . ${{ env.HELM_OPTIONS }}
        
  template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Helm
        uses: azure/setup-helm@v4
        
      - name: Template Helm Chart
        run: |
          helm template . ${{ env.HELM_OPTIONS }} > /dev/null && echo "Helm template successful"
          if [ $? -ne 0 ]; then echo "Chart contains errors. Aborting"; exit 1; fi
